pub mod build;
pub mod capture;
pub mod checks;
pub mod declarer;
pub mod error;
pub mod harness;
pub mod oracle;
pub mod outcome;
pub mod provision;
pub mod readyz;
pub mod runner;
pub mod scenario;
pub mod spawn;
pub mod subject;
pub mod subjects;
pub mod wire;

pub use build::{build_subject, ensure_go_available, subject_dir};
pub use capture::{CapturedConfirmation, ConfirmationCapture, Verdict};
pub use checks::{CheckContext, run_scenario};
pub use declarer::Declarer;
pub use error::{ConformanceError, Result};
pub use harness::{COMMAND_STREAM_NAME, EVENT_STREAM_NAME, IdentityHarness};
pub use oracle::{expected_step_verdicts, expected_verdict};
pub use outcome::{CheckId, CheckOutcome, CheckStatus, ConformanceReport};
pub use provision::provision;
pub use readyz::ReadyzProbe;
pub use runner::{AttachTarget, DEFAULT_TIMEOUT, run_attach};
pub use scenario::{ALL, Scenario, attach_default, parse_scenarios, spawn_default};
pub use spawn::{SpawnTarget, run_spawn};
pub use subject::{Subject, SubjectConfig};
pub use subjects::{accepted_event_subject, declare_subject, rejected_event_subject};
